version: '3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
    - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '3001:3001'
    command: npm run dev
    volumes:
      - ./backend:/backend
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: